env:
  global:
    - APPBUILDER_ASSET=default.ipa
    - APPBUILDER_ASSET_DOWNLOAD_PATH=s3://sil-stg-aps-files/default
    - APPBUILDER_ASSET_RESULT_PATH=s3://sil-stg-aps-files/stg/signed
    - APPBUILDER_SECRETS_PATH=s3://sil-stg-aps-secrets/travis/build

os: osx
language: shell

stages:
  - "Sign IPA"

jobs:
  include:
    - stage: "Sign IPA"
      if: branch = master
      language: generic
      before_install:
      - python --version
      - time ( ./install_aws_cli.sh )
      script:
        - time ( ./download_secrets.sh )
        - time ( ./download_asset.sh )
        - time ( ./resign_asset.sh )
        - time ( ./upload_asset.sh )
