os: osx

stages:
  - "Sign IPA"

jobs:
  include:
    - stage: "Sign IPA"
      if: branch = master
      language: generic
      before_install:
      - python --version
      - >
        time (
          wget "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
        )
      - which aws
      script:
        - time ( ./download_secrets.sh )
        - time ( ./download_asset.sh )
        - time ( ./resign_asset.sh )
        - time ( ./upload_asset.sh )
