os: osx

stages:
  - "Import Certificate"
  - "Set Keychain"

jobs:
  include:
    - stage: "Import Certificate"
      language: generic
      before_install:
      - python --version
      - >
        time (
          wget "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
        )
      script:
        - echo "Importing certificate"
        - time ( ./import_certificate.sh )
        - echo "Importing done!"

    - stage: "Set Keychain"
      language: generic
      script:
        - echo "Set Keychain"
        - time ( ./set_appbuilder_keychain.sh )
        - echo "Set done!"
