env:
  global:
    - APPBUILDER_ASSET=default.ipa
    - APPBUILDER_ASSET_DOWNLOAD_PATH=s3://sil-stg-aps-files/default
    - APPBUILDER_ASSET_RESULT_PATH=s3://sil-stg-aps-files/stg/signed
    - APPBUILDER_SECRETS_PATH=s3://sil-stg-aps-secrets/travis/build

os: osx
language: shell
install:
  - time ( ./install_aws_cli.sh )
  - time ( cd ansible && ansible-playbook playbook.yml )
before_script:
  - time ( ./download_secrets.sh )
  - time ( ./download_asset.sh )
script:
  - time ( ./builder.sh )
#  - time ( ./resign_asset.sh )
afer_script:
#   - time ( ./upload_asset.sh )
