version: 2

jobs:
  builder:
    branches:
      only:
        - builder
    macos:
      xcode: "11.1.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: echo local > /etc/ansible/hosts
      - run: cd ansible && ansible-playbook playbook.yml -c local
  build:
    branches:
      only:
        - master
    macos:
      xcode: "11.1.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew install wget
      - run: ./install_aws_cli.sh
      - run: ./download_secrets.sh
      - run: ./download_asset.sh
      - run: ./resign_asset.sh
      - run: ./upload_asset.sh
